### ISSUE TITLE
Limit on switch number?

### ISSUE THREAD

**Issue by sorriso93** [Supereg/homebridge-http-switch#4]
Hello
in the last days I added two more switches on my configuration and the last I added (some configuration as the previous ones with same hardware wemosd1 + relay) don't appear correctly on homebridge whereas I can reach them using http.
Do you know if there is a limit on how many switch can I use?
Problematic are "Irrigazione Camera", "WIFI extender", "Router Box".
My config.json extract is below:

{
            "accessory": "HTTP-SWITCH",
            "name": "Specchio Bagno Fede",
            "onUrl": "http://192.168.0.19/on",
            "offUrl": "http://192.168.0.19/off",
            "statusUrl": "http://192.168.0.19/status"
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Scrivania Max",
            "onUrl": "http://192.168.0.22/on",
            "offUrl": "http://192.168.0.22/off",
            "statusUrl": "http://192.168.0.22/status"
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Ventola Bagno Fede",
            "onUrl": "http://192.168.0.20/on",
            "offUrl": "http://192.168.0.20/off",
            "statusUrl": "http://192.168.0.20/status"
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "WIFI extender",
            "onUrl": "http://192.168.0.12/on1",
            "offUrl": "http://192.168.0.12/off1",
            "statusUrl": "http://192.168.0.12/status1"
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Irrigazione Camera",
            "onUrl": "http://192.168.0.12/on2",
            "offUrl": "http://192.168.0.12/off2",
            "statusUrl": "http://192.168.0.12/status2"
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Router Box",
            "onUrl": "http://192.168.0.26/on",
            "offUrl": "http://192.168.0.26/off",
            "statusUrl": "http://192.168.0.26/status"
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Luce Box",
            "onUrl": "http://192.168.0.27/on1",
            "offUrl": "http://192.168.0.27/off1",
            "statusUrl": "http://192.168.0.27/status1"
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Stampante Box",
            "onUrl": "http://192.168.0.27/on2",
            "offUrl": "http://192.168.0.27/off2",
            "statusUrl": "http://192.168.0.27/status2"
        },

**Comment by Supereg** [comment]
The only limit I can think of is coming from the HomeKit protocol itself. "A bridge must not expose more than 100 HAP accessory objects". So one Homebridge instance can only have a maximum of 100 accessories exposed.
Could that be the case for your setup?

**Comment by sorriso93** [comment]
You are right but I have 32 devices/entry in config.json, so this is not the case... It's running on a raspberry 1, maybe is this the problem? I noticed rarely, although homekit says is updating the status, I can switch on and off but are very slow, 1-2 minutes delay...
Is it correct that the status doesn't get updated? this is a common problem on all my switches... 
Is it ok a plain text page with the following string as a reply to state request, {"state": 1} or {"state": 0}.
many thanks

**Comment by Supereg** [comment]
Then I have no idea what’s going on. Are there any messages in the log which could give a hint? Maybe people at the hombridge repo can help with this.

I didn’t quite understand what you mean with whether it’s correct that the status doesn’t get updated. Could you explain this scenario with more details?

Currently the response to the status request must be a “0” or a “1”. Maybe in the future I could change this somewhat that it also works with more complex responses.

Greets
Andi

**Comment by sorriso93** [comment]
In the meantime I solved the status problem. Basically in homekit the icon of the switch was updated only when I clicked on it, changing the room and turning back it was back to off having it switched already on... Updating my arduino code to give a simple 0 or 1 result on the htttp page solved the problem (I used a json format before with brackets { }.
Regarding the slowness it seems the problem is due to a weak wifi signal, I will try some changes.
Many thanks I close the issue

**Comment by Supereg** [comment]
Yes indeed, because we only communicate via http in one way, the accessory doesn't get notified about changes not made via HomeKit. Only if HomeKit decides to update the state.
However HomeKit did implement a "notify" for some characteristics, which means that a service can update the state of it's characteristics to the HomeKit controller.
Some people solve this by querying the state of the http device every some seconds but I don't think this is an elegant version, especially if you have many switches.

I implemented the notify feature with an centralized http server which you can implement. Simply have a look at my [homebridge-http-notification-server](https://github.com/Supereg/homebridge-http-notification-server) and at the end of the README of the this repository of the switch itself.
I think you should be experienced enough to implement this into your Arduino code. After that you can notify the HomeKit controller of any state changes that happen on your Arduino.

Reach out to me if some things are unclear 😃 

When i got some more time, maybe I can implement some sort of regex pattern to allow a more complex response for experienced users.
