### ISSUE TITLE
Getting "keyword alert" at start

### ISSUE THREAD

**Issue by uspino2** [Supereg/homebridge-http-switch#44]
I have this component setup and working great on two Homebridge instances. In only one of them, I get this when starting:

`homebridge-http-base package.json does not contain the keyword 'homebridge-plugin'`

Anything I can do about it?

**Comment by Supereg** [comment]
’homebridge-http-base’ is a dependency which is shared across all of my homebridge-http-* plugins. However this package already brings a version of it in its own package.

It seems that you manually installed the base package globally with npm (what you shouldn’t need to do)? As this dependency does not expose any homebridge plugin itself and only delivers auxiliary functions the error message is expected behavior. To get rid of it just uninstall the global installation of ’homebridge-http-base’
